[project]
name = "idata2034-exam"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "shared",
    "server",
    "controller",
    "device",

    "pytest",
    "ruff",
    "basedpyright"
]

[tool.uv.sources]
shared = { workspace = true }
server = { workspace = true }
controller = { workspace = true }
device = { workspace = true }

[tool.uv.workspace]
members = [
    "shared",
    "server",
    "controller",
    "device",
]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
extend-select = [
    "ERA",
    "ASYNC",
    "A",
    "ARG",
    "N",
    "D"
]
extend-ignore = ["D211", "D213"]

[tool.pyright]
typeCheckingMode = "strict"
strictListInference = true
strictDictionaryInference = true
strictSetInference = true
analyzeUnannotatedFunctions = true
deprecateTypingAliases = true
reportMissingTypeStubs = false
